<?php

/**
 * @file
 * Requirements page for Animate CSS.
 */

/**
 * Implements hook_install().
 */
function animate_css_install() {

  $config = \Drupal::getContainer()->get('config.factory')->getEditable('animate_css.settings');
  // Check for Animate Library.
  $library = \Drupal::service('library.discovery')->getLibrariesByExtension('animate_css');
  $library_exists = file_exists(DRUPAL_ROOT . '/' . $library['animate.local']['css'][0]['data']);
  if (!$library_exists) {
    \Drupal::messenger()->addMessage(t('Animate CSS module requires the animate library. If you not using CDN link then <a href=":anim_link">Download animate library</a> and unzip into PROJECT_ROOT/libraries/animate.', [':anim_link' => $config->get('settings.default_url')]));
  }
}

/**
 * Implements hook_requirements().
 */
function animate_css_requirements($phase) {
  // Verify Animate is enabled.
  if ($phase == 'install') {
    return [];
  }

  $config = \Drupal::getContainer()->get('config.factory')->getEditable('animate_css.settings');
  $library_option = $config->get('settings.library');
  $library = \Drupal::service('library.discovery')->getLibrariesByExtension('animate_css');
  $library_exists = file_exists(DRUPAL_ROOT . '/' . $library['animate.local']['css'][0]['data']);

  if ($library_option == 'cdn') {
    return [];
  }

  return [
    'animate_library_downloaded' => [
      'title' => t('Animate library'),
      'value' => $library_exists ? t('Installed') : t('Not installed'),
      'description' => $library_exists ? '' : t('The Animate library needs to be <a href="@url">downloaded</a> and extracted into the PROJECT_ROOT/libraries/animate folder in your Drupal installation directory.', ['@url' => $config->get('settings.default_url')]),
      'severity' => $library_exists ? REQUIREMENT_OK : REQUIREMENT_ERROR,
    ],
  ];
}
